Libraries:
```{r}
library(dplyr)
library(leaflet)
library(sp)
library(ggmap)
library(maptools)
library(broom)
library(httr)
library(rgdal)
library(ggplot2)
library(tigris)
library(RColorBrewer)
library(ggpubr)
```
Load Data and Maps
```{r}
api <- 'AIzaSyC9UAYf9ihb5oDuKcWkORkcL9hOAtlTJe4'
register_google(key = api)
getOption("ggmap")

nyc_neighborhoods <- readOGR('data/map/NTA_map.geojson')
nyc_map <- get_map(location = c(lon = -74.00, lat = 40.71), maptype = "terrain", zoom = 11)

data = read.csv(file='data/clean/combined_dataset.csv')
```
Income and Internet:
```{r}
current <- select(data, c('Borough',
                          'Per.Capita.Income..in...',
                          'Home.Broadband.Adoption..', 
                          'Residential.Broadband.Choice.Average.by.NTA',
                          'Mobile.Dependent.Households..Percentage.of.Households.' ,
                          'Blocks.with.ISP.Reported.Speed.Availability.of...900.Mbps.in..',
                          'Public.Wi.Fi.in.NYC.Count', 
                          'Mobile.Broadband.Adoption..'))

plot1 <- ggplot(current, aes(x=Per.Capita.Income..in..., y=Home.Broadband.Adoption..)) +
  geom_point(aes(color=Borough), alpha=.6, size=1) +
  geom_smooth(method='glm', size=.5, se=FALSE, color='black') +
  xlab('Income') +
  ylab('Internet Adoption') +
  theme(text = element_text(size = 10))
  
plot2 <- ggplot(current, aes(x=Per.Capita.Income..in..., y=Residential.Broadband.Choice.Average.by.NTA)) +
  geom_point(aes(color=Borough), alpha=.6, size=1) +
  geom_smooth(method='glm', size=.5, se=FALSE, color='black') +
  xlab('Income') +
  ylab('# of Carriers') +
  theme(text = element_text(size = 10))

plot3 <- ggplot(current, aes(x=Per.Capita.Income..in..., y=Mobile.Dependent.Households..Percentage.of.Households.)) +
  geom_point(aes(color=Borough), alpha=.6, size=1) +
  geom_smooth(method='glm', size=.5, se=FALSE, color='black') +
  xlab('Income') +
  ylab('Mobile Dep. Households') +
  theme(text = element_text(size = 10))

plot4 <- ggplot(current, aes(x=Per.Capita.Income..in..., y=Blocks.with.ISP.Reported.Speed.Availability.of...900.Mbps.in..)) +
  geom_point(aes(color=Borough), alpha=.6, size=1) +
  geom_smooth(method='glm', size=.5, se=FALSE, color='black')  +
  xlab('Income') +
  ylab('Fast Speed Internet') +
  theme(text = element_text(size = 10))

plot5 <- ggplot(current, aes(x=Per.Capita.Income..in..., y=Public.Wi.Fi.in.NYC.Count)) +
  geom_point(aes(color=Borough), alpha=.6, size=1) +
  geom_smooth(method='glm', size=.5, se=FALSE, color='black') +
  xlab('Income') +
  ylab('Public WiFi Count') +
  theme(text = element_text(size = 10))

plot6 <- ggplot(current, aes(x=Per.Capita.Income..in..., y=Mobile.Broadband.Adoption..)) +
  geom_point(aes(color=Borough), alpha=.6, size=1) +
  geom_smooth(method='glm', size=.5, se=FALSE, color='black') +
  xlab('Income') +
  ylab('Mobile Internt Adoption') +
  theme(text = element_text(size = 10))

figure <- ggarrange(plot1, plot2, plot3, plot4, plot5, plot6, ncol=3, nrow=2, common.legend = TRUE, legend="bottom")

annotate_figure(figure,
                top = text_grob("Income and Internet Trends", size=20, face = "bold"))
```   

Poverty and Internet:
```{r}
current <- select(data, c('Borough', 
                          'Families.below.poverty.level..',
                          'Home.Broadband.Adoption..', 
                          'Residential.Broadband.Choice.Average.by.NTA',
                          'Mobile.Dependent.Households..Percentage.of.Households.' ,
                          'Blocks.with.ISP.Reported.Speed.Availability.of...900.Mbps.in..',
                          'Public.Wi.Fi.in.NYC.Count', 
                          'Mobile.Broadband.Adoption..'))

plot1 <- ggplot(current, aes(x=Families.below.poverty.level.., y=Home.Broadband.Adoption..)) +
  geom_point(aes(color=Borough), alpha=.6, size=1) +
  geom_smooth(method='glm', size=.5, se=FALSE, color='black') +
  xlab('Fam. Below Poverty Line') +
  ylab('Internet Adoption') +
  theme(text = element_text(size = 10))
  
plot2 <- ggplot(current, aes(x=Families.below.poverty.level.., y=Residential.Broadband.Choice.Average.by.NTA)) +
  geom_point(aes(color=Borough), alpha=.6, size=1) +
  geom_smooth(method='glm', size=.5, se=FALSE, color='black') +
  xlab('Fam. Below Poverty Line') +
  ylab('# of Carriers') +
  theme(text = element_text(size = 10))

plot3 <- ggplot(current, aes(x=Families.below.poverty.level.., y=Mobile.Dependent.Households..Percentage.of.Households.)) +
  geom_point(aes(color=Borough), alpha=.6, size=1) +
  geom_smooth(method='glm', size=.5, se=FALSE, color='black') +
  xlab('Fam. Below Poverty Line') +
  ylab('Mobile Dep. Households') +
  theme(text = element_text(size = 10))

plot4 <- ggplot(current, aes(x=Families.below.poverty.level.., y=Blocks.with.ISP.Reported.Speed.Availability.of...900.Mbps.in..)) +
  geom_point(aes(color=Borough), alpha=.6, size=1) +
  geom_smooth(method='glm', size=.5, se=FALSE, color='black')  +
  xlab('Fam. Below Poverty Line') +
  ylab('Fast Speed Internet') +
  theme(text = element_text(size = 10))

plot5 <- ggplot(current, aes(x=Families.below.poverty.level.., y=Public.Wi.Fi.in.NYC.Count)) +
  geom_point(aes(color=Borough), alpha=.6, size=1) +
  geom_smooth(method='glm', size=.5, se=FALSE, color='black') +
  xlab('Fam. Below Poverty Line') +
  ylab('Public WiFi Count') +
  theme(text = element_text(size = 10))

plot6 <- ggplot(current, aes(x=Families.below.poverty.level.., y=Mobile.Broadband.Adoption..)) +
  geom_point(aes(color=Borough), alpha=.6, size=1) +
  geom_smooth(method='glm', size=.5, se=FALSE, color='black') +
  xlab('Fam. Below Poverty Line') +
  ylab('Mobile Internt Adoption') +
  theme(text = element_text(size = 10))

figure <- ggarrange(plot1, plot2, plot3, plot4, plot5, plot6, ncol=3, nrow=2, common.legend = TRUE, legend="bottom")

annotate_figure(figure,
                top = text_grob("Poverty and Internet Trends", size=20, face = "bold"))
```   
```{r}
current = select(data, c('Borough', 'Families.below.poverty.level..', 'Blocks.with.ISP.Reported.Speed.Availability.of...900.Mbps.in..'))

ggplot(current, aes(x=Families.below.poverty.level.., y=Blocks.with.ISP.Reported.Speed.Availability.of...900.Mbps.in.., col=Borough)) +
  geom_point(size=2) +
  xlab('Families Below Poverty Line') +
  ylab('Internet availability > 900 Mbps') +
  ggtitle('Poverty Level and Fast Speed Internet')
```
Map of Internet Adoption Rate
```{r}
current <- select(data, c('Borough', 'Neighborhood.Name', 'Home.Broadband.Adoption..'))
names(current)[1] <- 'borough'
names(current)[2] <- 'neighborhood'
names(current)[3] <- 'points'

current$borough_num <- unclass(current$borough)
current$opacity_lvl <- current$points
current$opacity_lvl <- current$opacity_lvl^3

map_data <- geo_join(nyc_neighborhoods, current, "ntaname", "neighborhood")

pal <- colorFactor(palette = 'Set1',
                    unique(map_data@data$boroname))

leaflet(map_data) %>%
  addTiles() %>%
  addPolygons(popup = paste("Neighborhood:", map_data@data$ntaname, "<br>",
                            "Borough:", map_data@data$boroname, "<br>",
                            "Internet Adoption Rate:", paste(map_data@data$points*100, '%', sep=''), "<br>"),
              fillColor = ~pal(map_data@data$boroname),
              fillOpacity = map_data@data$points^3,
              highlightOptions = highlightOptions(weight = 3),
                                  color = "Black",
                                  weight = 1) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addLegend("bottomright", pal = pal, values = ~map_data@data$boroname)
```
